name: Build, Test, and Deploy Api
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - identification/server/**
env:
  PORT: 8080
  DOCKER_TAG: tracking/server
  IMAGE_NAME: delivery_service
  REPO_NAME: andreeam97
  
jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./identification/server
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME
    - name: run docker
      run: |
         docker run --env PORT=$PORT -p $PORT:$PORT -d $REPO_NAME/$IMAGE_NAME && \
          docker ps && sleep 5
#     - name: Run API Tests
#       id: run-newman
#       uses: anthonyvscode/newman-action@v1
#       with:
#         collection: assignment1/postman/collection.json
#         environment: assignment1/postman/environment.json
#         reporters: cli
#         iterationCount: 3

#     - name: Output summary to console
#       run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME
          
    - name: Configure SSH
      run: | 
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
      env:
          SSH_HOST: ${{ env.HOST_DNS }}
          SSH_USER: ${{ env.USERNAME }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 
      
    - name: Run docker image in AWS
      run: ssh ec2 'docker run --env PORT=$PORT -p $PORT:$PORT -d $REPO_NAME/$IMAGE_NAME:latest'
