name: Build, Test, and Deploy Api
on:
  push:
    branches:
      - master
    paths:
      - identification/server/**
env:
  PORT: 8080
  DOCKER_TAG: tracking/server
  
jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./identification/server
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $DOCKER_TAG
    - name: run docker
      run: |
         docker run --env PORT=PORT -p PORT:PORT -d $DOCKER_TAG && \
          docker ps && sleep 5
#     - name: Run API Tests
#       id: run-newman
#       uses: anthonyvscode/newman-action@v1
#       with:
#         collection: assignment1/postman/collection.json
#         environment: assignment1/postman/environment.json
#         reporters: cli
#         iterationCount: 3

#     - name: Output summary to console
#       run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Deploy to AWS
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${ { secrets.HOST_DNS }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        TARGET: ${ { secrets.TARGET_DIR }}
